/* Individual products extracted from catalogues */
const PRODUCTS = [
  // —— Stationeries page 0 ——
  { name: "A4 Copier Papers Double A", cat: "stationeries", page: 0 },
  { name: "Copier Papers Fujifilm A4 & A3", cat: "stationeries", page: 0 },
  { name: "A4 Copier Papers E-Paper", cat: "stationeries", page: 0 },
  { name: "A4 Copier Colored Papers", cat: "stationeries", page: 0 },
  { name: "Binding Hard Covers A4 & A3", cat: "stationeries", page: 0 },
  { name: "Binding Clear Covers A4 & A3", cat: "stationeries", page: 0 },
  { name: "A4 Display Books", cat: "stationeries", page: 0 },
  { name: "A4 Suspension File with Tags", cat: "stationeries", page: 0 },
  { name: "A4 Manila Folder", cat: "stationeries", page: 0 },
  { name: "A4 Magazine Folder", cat: "stationeries", page: 0 },
  { name: "A4 Foldable Magazine Folder", cat: "stationeries", page: 0 },
  { name: "A4 Mesh File Holder 3 Tier", cat: "stationeries", page: 0 },
  // page 1
  { name: "A4 Magazine Folder Mesh", cat: "stationeries", page: 1 },
  { name: "A4 Archive Storage Box", cat: "stationeries", page: 1 },
  { name: "School Exercise Books A4 & A5", cat: "stationeries", page: 1 },
  { name: "A4 Lecture Book 120 Pages", cat: "stationeries", page: 1 },
  { name: "A4 Olympic Books", cat: "stationeries", page: 1 },
  { name: "A4 Sketch Books", cat: "stationeries", page: 1 },
  { name: "A4 Executive Pad", cat: "stationeries", page: 1 },
  { name: "Writing Pad A4 & A5", cat: "stationeries", page: 1 },
  { name: "Hardcover Notebooks A4, A5 & A6", cat: "stationeries", page: 1 },
  { name: "Spiral Notebooks", cat: "stationeries", page: 1 },
  { name: "Olympic Cash Receipt Book 616", cat: "stationeries", page: 1 },
  { name: "Olympic Cash Receipt Book 615", cat: "stationeries", page: 1 },
  // page 2
  { name: "Olympic Cash Receipt Book 614", cat: "stationeries", page: 2 },
  { name: "Olympic Cash Receipt Book 613", cat: "stationeries", page: 2 },
  { name: "A4 Wooden Clip Board with Metal Clip", cat: "stationeries", page: 2 },
  { name: "PVC A4 Clip Boards Assorted", cat: "stationeries", page: 2 },
  { name: "Laminating Pouches", cat: "stationeries", page: 2 },
  { name: "Gold Kraft Envelopes", cat: "stationeries", page: 2 },
  { name: "Datamax Gold Kraft Envelopes", cat: "stationeries", page: 2 },
  { name: "Window Envelopes White", cat: "stationeries", page: 2 },
  { name: "Post-It Pads", cat: "stationeries", page: 2 },
  { name: "Time Cards", cat: "stationeries", page: 2 },
  { name: "Time Card Racks", cat: "stationeries", page: 2 },
  { name: "Whiteboards Porcelain-Coated", cat: "stationeries", page: 2 },
  // page 3
  { name: "Time Card Machines", cat: "stationeries", page: 3 },
  { name: "A4 Laminating Machines", cat: "stationeries", page: 3 },
  { name: "A4 Binding Machines", cat: "stationeries", page: 3 },
  { name: "Packing Tape Dispenser", cat: "stationeries", page: 3 },
  { name: "Brown Packing Tapes", cat: "stationeries", page: 3 },
  { name: "Clear Packing Tapes", cat: "stationeries", page: 3 },
  { name: "Binding Tapes Assorted", cat: "stationeries", page: 3 },
  { name: "Cloth Tape Assorted", cat: "stationeries", page: 3 },
  { name: "Duct Tapes", cat: "stationeries", page: 3 },
  { name: "Masking Tapes", cat: "stationeries", page: 3 },
  { name: "Deli Calculators", cat: "stationeries", page: 3 },
  { name: "Casio Scientific Calculator FX-100MS", cat: "stationeries", page: 3 },
  // page 4
  { name: "PVC ID Tags", cat: "stationeries", page: 4 },
  { name: "White Board Duster", cat: "stationeries", page: 4 },
  { name: "Stapler Set", cat: "stationeries", page: 4 },
  { name: "Stapler", cat: "stationeries", page: 4 },
  { name: "2 Hole Puncher", cat: "stationeries", page: 4 },
  { name: "Whiteboard Cleaner", cat: "stationeries", page: 4 },
  { name: "PVC Clear Key Tags Assorted with Rack", cat: "stationeries", page: 4 },
  { name: "Key Tags Ring Assorted", cat: "stationeries", page: 4 },
  { name: "PVC Clear Key Tags Assorted", cat: "stationeries", page: 4 },
  { name: "Stamp Inks Assorted Colors", cat: "stationeries", page: 4 },
  { name: "Stamp Pads Assorted Color Pads", cat: "stationeries", page: 4 },
  { name: "Paper Glue", cat: "stationeries", page: 4 },
  // page 5
  { name: "Sticky Glue", cat: "stationeries", page: 5 },
  { name: "Super Glue", cat: "stationeries", page: 5 },
  { name: "White Outs", cat: "stationeries", page: 5 },
  { name: "Water 12-Colors", cat: "stationeries", page: 5 },
  { name: "Permanent Markers Assorted Colors", cat: "stationeries", page: 5 },
  { name: "White Board Markers Assorted Colors", cat: "stationeries", page: 5 },
  { name: "Metal Paint Markers Assorted Colors", cat: "stationeries", page: 5 },
  { name: "Smart Pen Style Highlighters Assorted Colors", cat: "stationeries", page: 5 },
  { name: "Classic Pastel Highlighters Assorted Colors", cat: "stationeries", page: 5 },
  { name: "Crayons", cat: "stationeries", page: 5 },
  { name: "Colored Pencils", cat: "stationeries", page: 5 },
  { name: "Mechanical Pencils Set", cat: "stationeries", page: 5 },
  // page 6
  { name: "HB Pencils", cat: "stationeries", page: 6 },
  { name: "2B Pencils", cat: "stationeries", page: 6 },
  { name: "4-in-1 Pen Assorted Color", cat: "stationeries", page: 6 },
  { name: "6-in-1 Pen Assorted Color", cat: "stationeries", page: 6 },
  { name: "Ball Point Pen Black, Blue & Red", cat: "stationeries", page: 6 },
  { name: "Retractable Biro Black, Blue & Red", cat: "stationeries", page: 6 },
  { name: "Gel Biros Black, Blue & Red", cat: "stationeries", page: 6 },
  { name: "Triangular Ruler 30cm", cat: "stationeries", page: 6 },
  { name: "Wooden Ruler 30cm", cat: "stationeries", page: 6 },
  { name: "Clear Plastic Rulers", cat: "stationeries", page: 6 },
  { name: "Metal Rulers", cat: "stationeries", page: 6 },
  { name: "Black Board / White Board Ruler", cat: "stationeries", page: 6 },
  // page 7
  { name: "Spiral Binding Combs Assorted", cat: "stationeries", page: 7 },
  { name: "Cloth Scissors Stainless Steel", cat: "stationeries", page: 7 },
  { name: "Paper Scissors Stainless Steel", cat: "stationeries", page: 7 },
  { name: "Math Sets", cat: "stationeries", page: 7 },
  { name: "Blu Tuck", cat: "stationeries", page: 7 },
  { name: "Bull Dog Clips", cat: "stationeries", page: 7 },
  { name: "Round Paper Clips", cat: "stationeries", page: 7 },
  { name: "Push Pins Assorted Colors", cat: "stationeries", page: 7 },
  { name: "Push Pins Stainless Steel", cat: "stationeries", page: 7 },
  { name: "Staples 24/6 & 26/6", cat: "stationeries", page: 7 },
  { name: "Sharpener 1 Hole & 2 Hole", cat: "stationeries", page: 7 },
  { name: "Pencil Eraser White", cat: "stationeries", page: 7 },

  // —— Inks & Toners ——
  { name: "Ink Cartridge HP 61 Black / Tri-Color", cat: "inks", page: 0 },
  { name: "Ink Cartridge HP 62 Black / Tri-Color", cat: "inks", page: 0 },
  { name: "Ink Cartridge HP 63 Black / Tri-Color", cat: "inks", page: 0 },
  { name: "Ink Cartridge HP 65 Black / Tri-Color", cat: "inks", page: 0 },
  { name: "Ink Cartridge HP 67 Black / Tri-Color", cat: "inks", page: 0 },
  { name: "Ink Cartridge HP 564 Black / All Colors", cat: "inks", page: 0 },
  { name: "Ink Cartridge HP 955 Black / All Colors", cat: "inks", page: 0 },
  { name: "Ink Cartridge Pixma Canon 645 Black / 646 Color", cat: "inks", page: 0 },
  { name: "Ink Cartridge Pixma Canon 650 / 651", cat: "inks", page: 0 },
  { name: "Ink Cartridge Brother LC133 Black / All Colors", cat: "inks", page: 0 },
  { name: "Ribbon Cartridge Epson LQ310 Black", cat: "inks", page: 0 },
  { name: "Toner Cartridge HP 05A Black", cat: "inks", page: 0 },
  { name: "Toner Cartridge HP 17A Black", cat: "inks", page: 1 },
  { name: "Toner Drum Unit HP 19A Black", cat: "inks", page: 1 },
  { name: "Toner Cartridge HP 26A Black", cat: "inks", page: 1 },
  { name: "Toner Cartridge HP 30A Black", cat: "inks", page: 1 },
  { name: "Toner Drum Unit HP 32A Black", cat: "inks", page: 1 },
  { name: "Toner Cartridge HP 35A Black", cat: "inks", page: 1 },
  { name: "Toner Cartridge HP 36A Black", cat: "inks", page: 1 },
  { name: "Toner Cartridge HP 42A Black", cat: "inks", page: 1 },
  { name: "Toner Cartridge HP 55A Black", cat: "inks", page: 1 },
  { name: "Toner Cartridge HP 76A Black", cat: "inks", page: 1 },
  { name: "Toner Cartridge HP 78A Black", cat: "inks", page: 1 },
  { name: "Toner Cartridge HP 79A Black", cat: "inks", page: 1 },
  { name: "Toner Cartridge HP 80A Black", cat: "inks", page: 2 },
  { name: "Toner Cartridge HP 83A Black", cat: "inks", page: 2 },
  { name: "Toner Cartridge HP 85A Black", cat: "inks", page: 2 },
  { name: "Toner Cartridge HP 90A Black", cat: "inks", page: 2 },
  { name: "Toner Cartridge HP 148A Black", cat: "inks", page: 2 },
  { name: "Toner Cartridge HP 125A Black / All Colors", cat: "inks", page: 2 },
  { name: "Toner Cartridge HP 128A Black / All Colors", cat: "inks", page: 2 },
  { name: "Toner Cartridge HP 130A Black / All Colors", cat: "inks", page: 2 },
  { name: "Toner Cartridge HP 131A Black / All Colors", cat: "inks", page: 2 },
  { name: "Toner Cartridge HP 201A Black / All Colors", cat: "inks", page: 2 },
  { name: "Toner Cartridge HP 202A Black / All Colors", cat: "inks", page: 2 },
  { name: "Toner Cartridge HP 204A Black / All Colors", cat: "inks", page: 2 },
  { name: "Toner Cartridge HP 206A Black / All Colors", cat: "inks", page: 3 },
  { name: "Toner Cartridge HP 210A Black / All Colors", cat: "inks", page: 3 },
  { name: "Toner Cartridge HP 215A Black / All Colors", cat: "inks", page: 3 },
  { name: "Toner Cartridge HP 304A Black / All Colors", cat: "inks", page: 3 },
  { name: "Toner Cartridge HP 305A Black / All Colors", cat: "inks", page: 3 },
  { name: "Toner Cartridge HP 312A Black / All Colors", cat: "inks", page: 3 },
  { name: "Toner Cartridge HP 410A Black / All Colors", cat: "inks", page: 3 },
  { name: "Toner Cartridge HP 416A Black / All Colors", cat: "inks", page: 3 },
  { name: "Toner Cartridge Brother TN2430 Black", cat: "inks", page: 3 },
  { name: "Toner Cartridge Brother TN2450 Black", cat: "inks", page: 3 },
  { name: "Toner Cartridge Brother TN2060 Black", cat: "inks", page: 3 },
  { name: "Toner Cartridge Konica TN328 Black / All Colors", cat: "inks", page: 3 },

  // —— IT Accessories ——
  { name: "External Hard Drive Passport 1TB", cat: "it", page: 0 },
  { name: "External Hard Drive Toshiba 2TB", cat: "it", page: 0 },
  { name: "Flash Drive Strontium 8GB", cat: "it", page: 0 },
  { name: "Flash Drive Strontium 16GB", cat: "it", page: 0 },
  { name: "Flash Drive Strontium 32GB", cat: "it", page: 0 },
  { name: "Flash Drive Strontium 64GB", cat: "it", page: 0 },
  { name: "Flash Drive Toshiba 16GB", cat: "it", page: 0 },
  { name: "Memory Card Strontium 8GB", cat: "it", page: 0 },
  { name: "Memory Card Strontium 16GB", cat: "it", page: 0 },
  { name: "Memory Card Strontium 32GB", cat: "it", page: 0 },
  { name: "Memory Card Strontium 64GB", cat: "it", page: 0 },
  { name: "Memory Card SanDisk 8GB", cat: "it", page: 0 },
  { name: "Memory Card SanDisk 16GB", cat: "it", page: 1 },
  { name: "Memory Card SanDisk 32GB", cat: "it", page: 1 },
  { name: "Memory Card SanDisk 64GB", cat: "it", page: 1 },
  { name: "Wireless Mouse Anko", cat: "it", page: 1 },
  { name: "Wired Mouse Anko", cat: "it", page: 1 },
  { name: "Wireless Mouse & Keyboard Combo", cat: "it", page: 1 },
  { name: "Wired Mouse & Keyboard Combo", cat: "it", page: 1 },
  { name: "Gaming Mouse & Keyboard Combo", cat: "it", page: 1 },
  { name: "Wireless Mouse Logitech", cat: "it", page: 1 },
  { name: "Wired Mouse Logitech", cat: "it", page: 1 },
  { name: "Wireless Mouse & Keyboard Logitech Combo", cat: "it", page: 1 },
  { name: "Wired Keyboard Logitech", cat: "it", page: 1 },
  { name: "Wired Mouse & Keyboard Logitech Combo MK120", cat: "it", page: 2 },
  { name: "HP Deskjet Printer", cat: "it", page: 2 },
  { name: "HP Laserjet Printer", cat: "it", page: 2 },
  { name: "Canon Deskjet Printer", cat: "it", page: 2 },
  { name: "UPS Power Saver", cat: "it", page: 2 },
  { name: "Monitor", cat: "it", page: 2 },
  { name: "Desktop PC", cat: "it", page: 2 },
  { name: "Mouse Pad", cat: "it", page: 2 },
  { name: "Type-C Adapter Connection", cat: "it", page: 2 },
  { name: "Type-C USB Connection", cat: "it", page: 2 },
  { name: "Type-C to Type-C Connection", cat: "it", page: 2 },
  { name: "Micro USB Connection", cat: "it", page: 2 },

  // —— Catering & Cleaning ——
  { name: "Mini Jumbo Toilet Tissues", cat: "catering", page: 0 },
  { name: "Economic Tissues", cat: "catering", page: 0 },
  { name: "Hand Paper Towel", cat: "catering", page: 0 },
  { name: "Paper Serviettes", cat: "catering", page: 0 },
  { name: "Disposable Form Products (Plates)", cat: "catering", page: 0 },
  { name: "Disposable Aluminium Foil Pans", cat: "catering", page: 0 },
  { name: "Disposable Form Cutlery", cat: "catering", page: 0 },
  { name: "Disposable Form Coffee Cups", cat: "catering", page: 0 },
  { name: "Disposable Brown Paper Bags", cat: "catering", page: 0 },
  { name: "Disposable Plastic Plates with Lid", cat: "catering", page: 0 },
  { name: "Cling Wrap", cat: "catering", page: 0 },
  { name: "Aluminium Foil Wrap", cat: "catering", page: 0 },
  { name: "Disposable Hair Nets", cat: "catering", page: 1 },
  { name: "Disposable Shoe Cover", cat: "catering", page: 1 },
  { name: "Shrink Wrap Clear", cat: "catering", page: 1 },
  { name: "Shrink Wrap Dark", cat: "catering", page: 1 },
  { name: "Disposable Garbage Bag Black", cat: "catering", page: 1 },
  { name: "Disposable Garbage Bag Yellow", cat: "catering", page: 1 },
  { name: "Disposable Plastic Aprons", cat: "catering", page: 1 },
  { name: "Wheelie Bins Assorted", cat: "catering", page: 1 },
  { name: "Wringer Mop Bucket 15L", cat: "catering", page: 1 },
  { name: "Stainless Steel Metal Bucket with Handle", cat: "catering", page: 1 },
  { name: "Mop Head", cat: "catering", page: 1 },
  { name: "Mop Handle", cat: "catering", page: 1 },
  { name: "Rotating Detachable Mop", cat: "catering", page: 2 },
  { name: "Window Glass Squeegee", cat: "catering", page: 2 },
  { name: "Microfiber Dust Mop", cat: "catering", page: 2 },
  { name: "Corn/Fiber Broom", cat: "catering", page: 2 },
  { name: "Lobby Dust Pan", cat: "catering", page: 2 },
  { name: "Lapwing Yard Broom", cat: "catering", page: 2 },
  { name: "Maxi-Lok Push Broom", cat: "catering", page: 2 },
  { name: "PVC Bristle Hard Broom", cat: "catering", page: 2 },
  { name: "Household Indoor Broom", cat: "catering", page: 2 },
  { name: "Floor Scrub Brush", cat: "catering", page: 2 },
  { name: "Scrub Brush Non-Slip Handle", cat: "catering", page: 2 },
  { name: "Dish Brush", cat: "catering", page: 2 },
  { name: "Dustpan & Broom", cat: "catering", page: 3 },
  { name: "Nylon Toilet Brush with Holder", cat: "catering", page: 3 },
  { name: "Oil Absorbent Boom", cat: "catering", page: 3 },
  { name: "Oil Absorbent Sheets", cat: "catering", page: 3 },
  { name: "500ml Spray Bottle Container Trigger", cat: "catering", page: 3 },
  { name: "Microfiber Cleaning Cloth", cat: "catering", page: 3 },
  { name: "Coir Door Mats", cat: "catering", page: 3 },
  { name: "Rubber Door Mats", cat: "catering", page: 3 },
  { name: "Bathroom Rubber Mats", cat: "catering", page: 3 },
  { name: "Cotton Indoor Mats", cat: "catering", page: 3 },
  { name: "Shower Curtains", cat: "catering", page: 3 },
  { name: "Chux Wipes", cat: "catering", page: 3 },

  // —— PPE ——
  { name: "Disposable P2 Dust Mask", cat: "ppe", page: 0 },
  { name: "Disposable P1 Dust Mask", cat: "ppe", page: 0 },
  { name: "Disposable KN95 Dust Mask", cat: "ppe", page: 0 },
  { name: "Disposable Medical Face Mask", cat: "ppe", page: 0 },
  { name: "Respirator Mask Double", cat: "ppe", page: 0 },
  { name: "Respirator Mask Single", cat: "ppe", page: 0 },
  { name: "Disposable Latex PF Gloves", cat: "ppe", page: 0 },
  { name: "Disposable Vinyl Gloves", cat: "ppe", page: 0 },
  { name: "Rubber Gloves", cat: "ppe", page: 0 },
  { name: "PVC Rubber Gloves Long", cat: "ppe", page: 0 },
  { name: "PVC Rubber Gloves Short", cat: "ppe", page: 0 },
  { name: "Working Palm Gloves", cat: "ppe", page: 0 },
  { name: "PVC Welding Gloves", cat: "ppe", page: 1 },
  { name: "Cotton Hand Gloves Plain White", cat: "ppe", page: 1 },
  { name: "Cotton Hand Gloves Dotted", cat: "ppe", page: 1 },
  { name: "Working Gloves Reusable", cat: "ppe", page: 1 },
  { name: "Protective Gloves", cat: "ppe", page: 1 },
  { name: "Headband Ear Muff", cat: "ppe", page: 1 },
  { name: "Ear Plug Corded", cat: "ppe", page: 1 },
  { name: "Ear Plug", cat: "ppe", page: 1 },
  { name: "Safety Helmets", cat: "ppe", page: 1 },
  { name: "Safety Eye Glass Clear", cat: "ppe", page: 1 },
  { name: "Safety Eye Glass Dark", cat: "ppe", page: 1 },
  { name: "Eye Cup Oxy/Acetylene Goggles", cat: "ppe", page: 1 },
  { name: "Welding Goggles", cat: "ppe", page: 2 },
  { name: "Welding Helmet", cat: "ppe", page: 2 },
  { name: "Welding Lens Dark", cat: "ppe", page: 2 },
  { name: "Welding Lens Clear", cat: "ppe", page: 2 },
  { name: "Full Body Safety Harness", cat: "ppe", page: 2 },
  { name: "Rubber Gumboots", cat: "ppe", page: 2 },
  { name: "Rubber Gumboots with Steel Tip", cat: "ppe", page: 2 },
  { name: "Safety Boots", cat: "ppe", page: 2 },
  { name: "Rain Coat Long", cat: "ppe", page: 2 },
  { name: "Rain Coat 2-Piece", cat: "ppe", page: 2 },
  { name: "Working Overalls", cat: "ppe", page: 2 },
  { name: "Hard Yakka Clothing", cat: "ppe", page: 2 }
];

const CATALOG_PAGES = {
  stationeries: [
    'PRODUCT%20CATALOG%202025%20-%20General%20Stationeries%20(pdf.io)%20(1)/PRODUCT%20CATALOG%202025%20-%20General%20Stationeries-0.jpg',
    'PRODUCT%20CATALOG%202025%20-%20General%20Stationeries%20(pdf.io)%20(1)/PRODUCT%20CATALOG%202025%20-%20General%20Stationeries-1.jpg',
    'PRODUCT%20CATALOG%202025%20-%20General%20Stationeries%20(pdf.io)%20(1)/PRODUCT%20CATALOG%202025%20-%20General%20Stationeries-2.jpg',
    'PRODUCT%20CATALOG%202025%20-%20General%20Stationeries%20(pdf.io)%20(1)/PRODUCT%20CATALOG%202025%20-%20General%20Stationeries-3.jpg',
    'PRODUCT%20CATALOG%202025%20-%20General%20Stationeries%20(pdf.io)%20(1)/PRODUCT%20CATALOG%202025%20-%20General%20Stationeries-4.jpg',
    'PRODUCT%20CATALOG%202025%20-%20General%20Stationeries%20(pdf.io)%20(1)/PRODUCT%20CATALOG%202025%20-%20General%20Stationeries-5.jpg',
    'PRODUCT%20CATALOG%202025%20-%20General%20Stationeries%20(pdf.io)%20(1)/PRODUCT%20CATALOG%202025%20-%20General%20Stationeries-6.jpg',
    'PRODUCT%20CATALOG%202025%20-%20General%20Stationeries%20(pdf.io)%20(1)/PRODUCT%20CATALOG%202025%20-%20General%20Stationeries-7.jpg'
  ],
  inks: [
    'PRODUCT%20CATALOG%202025%20-%20Inks%20%26%20Toners/PRODUCT%20CATALOG%202025-0.jpg',
    'PRODUCT%20CATALOG%202025%20-%20Inks%20%26%20Toners/PRODUCT%20CATALOG%202025-1.jpg',
    'PRODUCT%20CATALOG%202025%20-%20Inks%20%26%20Toners/PRODUCT%20CATALOG%202025-2.jpg',
    'PRODUCT%20CATALOG%202025%20-%20Inks%20%26%20Toners/PRODUCT%20CATALOG%202025-3.jpg'
  ],
  it: [
    'PRODUCT%20CATALOG%202025%20-%20IT%20ACCESSERIES%20(pdf.io)/PRODUCT%20CATALOG%202025%20-%20IT%20ACCESSERIES-0.jpg',
    'PRODUCT%20CATALOG%202025%20-%20IT%20ACCESSERIES%20(pdf.io)/PRODUCT%20CATALOG%202025%20-%20IT%20ACCESSERIES-1.jpg',
    'PRODUCT%20CATALOG%202025%20-%20IT%20ACCESSERIES%20(pdf.io)/PRODUCT%20CATALOG%202025%20-%20IT%20ACCESSERIES-2.jpg'
  ],
  catering: [
    'PRODUCT%20CATALOG%202025%20-CATERING%20%26%20PAPER%20PRODUCTS%20(1)%20(pdf.io)/PRODUCT%20CATALOG%202025%20-CATERING%20%26%20PAPER%20PRODUCTS%20(1)-0.jpg',
    'PRODUCT%20CATALOG%202025%20-CATERING%20%26%20PAPER%20PRODUCTS%20(1)%20(pdf.io)/PRODUCT%20CATALOG%202025%20-CATERING%20%26%20PAPER%20PRODUCTS%20(1)-1.jpg',
    'PRODUCT%20CATALOG%202025%20-CATERING%20%26%20PAPER%20PRODUCTS%20(1)%20(pdf.io)/PRODUCT%20CATALOG%202025%20-CATERING%20%26%20PAPER%20PRODUCTS%20(1)-2.jpg',
    'PRODUCT%20CATALOG%202025%20-CATERING%20%26%20PAPER%20PRODUCTS%20(1)%20(pdf.io)/PRODUCT%20CATALOG%202025%20-CATERING%20%26%20PAPER%20PRODUCTS%20(1)-3.jpg'
  ],
  ppe: [
    'PRODUCT%20CATALOG%202025%20-PPE%20CONSUMABLES%20(1)-0.jpg',
    'PRODUCT%20CATALOG%202025%20-PPE%20CONSUMABLES%20(1)-1.jpg',
    'PRODUCT%20CATALOG%202025%20-PPE%20CONSUMABLES%20(1)-2.jpg'
  ]
};

const CAT_LABELS = {
  stationeries: 'Stationeries',
  inks: 'Inks & Toners',
  it: 'IT & Printers',
  catering: 'Catering & Cleaning',
  ppe: 'PPE Consumables'
};
